coverage:
  precision: 2
  round: up
  range: "50...90"
  status:
    project:
      default:
        threshold: 1
  ignore:
    - "**/pb" # ignore pb generated code directories
    - "**/*.pb.go" # ignore generated pb code
    - "**/*_test.go" # ignore tests